<a href="/films/"><< Назад к списку</a>
<?php if (!empty($data['films'])): ?>
    <?php foreach ($data['films'] as $film): ?>
        <div style="margin-top: 20px; border-bottom: 2px dashed #DADADA;">
            <a href="/films/view/<?=$film['id']?>"><?=$film['title']?></a>
            <p>(<?=$film['year']?>)</p>
            <p><b>Format:</b> <?=$film['format']?></p>
            <p><b>Actors:</b> <?=$film['actors']?></p>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
