<h3>Add Film</h3><br>
<form action="" method="post">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" id="title" value="" class="form-control">
    </div>

    <div class="form-group">
        <label for="year">Year</label>
        <input type="text" name="year" id="year" value="" class="form-control">
    </div>

    <div class="form-group">
        <label for="format">Format</label>
        <select name="format" id="format" class="form-control">
            <?php foreach ($data['formats'] as $format) { ?>
                <option value="<?=$format['id']?>"><?=$format['name']?></option>
            <?php } ?>
        </select>
    </div>

    <div class="form-group">
        <label for="actors">Actors</label>
        <textarea name="actors" id="actors" class="form-control"></textarea>
    </div>

    <input type="submit" class="btn btn-success" value="Add">
</form>