<form action="/admin/films/" class="navbar-form navbar-right">
    <div class="form-group">
        <label for="sort">Sort: </label>
        <select name="sort" id="sort" class="form-control">
            <option value="asc" <?php if ($_GET && $_GET['sort'] == 'asc') { ?>selected<?php } ?>>Order A - Z</option>
            <option value="desc" <?php if ($_GET && $_GET['sort'] == 'desc') { ?>selected<?php } ?>>Order Z - A</option>
            <option value="return" <?php if ($_GET && $_GET['sort'] == 'return') { ?>selected<?php } ?>>Order to Add</option>
        </select>
    </div>
    <button type="submit" class="btn btn-success">Go!</button>
</form>

<h3>Film List:</h3><br>

<table class="table table-striped" style="width: 600px;">
    <?php foreach ($data['films'] as $film) { ?>
        <tr>
            <td><b><?=$film['title']?></b></td>
            <td align="right">
                <a href="/admin/films/view/<?= $film['id'] ?>"><button class="btn btn-sm btn-info">About</button></a>
                <a href="/admin/films/edit/<?= $film['id'] ?>"><button class="btn btn-sm btn-primary">Edit</button></a>
                <a href="/admin/films/delete/<?= $film['id'] ?>" onclick="return confirmDelete();"><button class="btn btn-sm btn-warning">Delete</button></a>
            </td>
        </tr>
    <?php } ?>
</table>

<br>

<div>
    <a href="/admin/films/add/"><button class="btn btn-sm btn-success">New Film</button></a>
    <a href="/admin/films/addfromfile/"><button class="btn btn-sm btn-success">Load From File</button></a>
</div>

