<h3>Edit Film</h3><br>
<form action="" method="post">
    <input type="hidden" name="id" value="<?=$data['film']['id']?>">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" id="title" value="<?=$data['film']['title']?>" class="form-control">
    </div>

    <div class="form-group">
        <label for="year">Year</label>
        <input type="text" name="year" id="year" value="<?=$data['film']['year']?>" class="form-control">
    </div>

    <div class="form-group">
        <label for="format">Format</label>
        <select name="format" id="format" class="form-control">
            <?php foreach ($data['formats'] as $format) { ?>
                <option value="<?=$format['id']?>" <?php if ($format['name']==$data['film']['format']) { ?> selected <?php } ?>><?=$format['name']?></option>
            <?php } ?>
        </select>
    </div>

    <div class="form-group">
        <label for="actors">Actors</label>
        <textarea name="actors" id="actors" class="form-control"><?=$data['film']['actors']?></textarea>
    </div>

    <input type="submit" class="btn btn-success">
</form>