<form action="/films/" class="navbar-form navbar-right">
    <div class="form-group">
        <label for="sort">Sort: </label>
        <select name="sort" id="sort" class="form-control">
            <option value="asc" <?php if ($_GET && $_GET['sort'] == 'asc') { ?> selected <?php } ?>>Order A - Z</option>
            <option value="desc" <?php if ($_GET && $_GET['sort'] == 'desc') { ?> selected <?php } ?>>Order Z - A</option>
            <option value="return" <?php if ($_GET && $_GET['sort'] == 'return') { ?>selected<?php } ?>>Order to Add</option>
        </select>
    </div>
    <button type="submit" class="btn btn-success">Go!</button>
</form>

<?php foreach($data['films'] as $film) { ?>

    <div style="margin-top: 20px; border-bottom: 2px dashed #DADADA;">
        <a href="/films/view/<?=$film['id']?>"><?=$film['title']?></a>
        <p>(<?=$film['year']?>)</p>
        <p><b>Format:</b> <?=$film['format']?></p>
        <p><b>Actors:</b> <?=$film['actors']?></p>
    </div>

<?php } ?>
